server:
  port: ${SERVER_PORT:8101}

spring:
  application:
    name: product
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8084/realms/ecommerce}
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    username: ${MONGO_USERNAME:admin}
    password: ${MONGO_PASSWORD:admin}
    database: ${MONGO_DATABASE:product}
    authentication-database: ${MONGO_AUTH_DATABASE:admin}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    template:
      observation-enabled: true
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

kafka:
  topics:
    product: product

management:
  server:
    port: ${MANAGEMENT_PORT:8102}
