spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

kafka:
  topics:
    product: product

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  logging:
    export:
      otlp:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  structured:
    format:
      console: ecs
