server:
  port: ${SERVER_PORT:8170}

spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    order: order
    user: user
    stock-level: stock-level

management:
  server:
    port: ${MANAGEMENT_PORT:8171}
