server:
  port: ${SERVER_PORT:8110}

spring:
  application:
    name: search
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    product: product

management:
  server:
    port: ${MANAGEMENT_PORT:8111}
