name: Quality (product service)

on:
  push:
    paths:
      - 'services/product/**'
      - 'libs/**'
  pull_request:
    paths:
      - 'services/product/**'
      - 'libs/**'

jobs:
  quality:
    uses: ./.github/workflows/quality-reusable.yml
    with:
      service-path: services/product
      service-name: product
